name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # only publish on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # required for trusted publishing (optional)
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PDM
        run: |
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pdm install

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: pdm run twine upload dist/*
